services:
  db:
    image: postgres:16-alpine
    container_name: etl-postgres
    environment:
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl -d etl_db"]
      interval: 2s
      timeout: 3s
      retries: 30

volumes:
  pgdata: